### PR TITLE
Misc improvements in phrasing, small spelling fixes, and fixes to use the correct classifier in the notebook

### PR DESCRIPTION
**Pull request by hoechenberger**

### CODE REVIEW

**Comment by hoechenberger** [comment]
@maikia Travis failed du to a cell execution timeout; I believe this is due to the `predict()` call taking too long for the `MultiOutputClassifier` we talked about…

**Comment by maikia** [comment]
> @maikia Travis failed du to a cell execution timeout; I believe this is due to the `predict()` call taking too long for the `MultiOutputClassifier` we talked about…

Thanks @hoechenberger 
I just added the update to the master to only use the subset of the data. Can you please merge and see if that solves the issue. Thanks

**Comment by hoechenberger** [comment]
Merging jupyter notebooks? Hey, I didn't sign up for this ;)

Ok will try

**Comment by maikia** [comment]
Thanks @hoechenberger

**Pull request merged**
