### PR TITLE
added environments specifics missing from requirements.txt

### PR DESCRIPTION
**Pull request by maikia**
on the AMI pipeline it is now difficult to update the image using environment.yml file.
This .txt file adds the libraries from environment.yml missing from requirements.txt

cc @tomMoral

### CODE REVIEW

**Review by tomMoral — APPROVED** [review]
I would call it `extra_libraries.txt` instead but else it is fine for me.

**Comment by agramfort** [comment]
why do you say it's difficult?

**Comment by tomMoral** [comment]
It is not that it is difficult, it is just that the command fail and I don't know why :sweat: 
So let's keep it simple with pip for now?

**Comment by agramfort** [comment]
incompatible binaries on pypi?

**Comment by tomMoral** [comment]
On `conda-forge` and `default` I guess but yes.

**Comment by maikia** [comment]
Thanks @agramfort and @tomMoral

**Pull request merged**
