### PR TITLE
typos

### PR DESCRIPTION
**Pull request by hichamjanati**
fixed some typos

### CODE REVIEW

**Comment by lucyleeow** [comment]
@maikia @agramfort do either of you know who removed the timeout in the travis file?
```
    - jupyter nbconvert --execute meg_starting_kit.ipynb 
      --ExecutePreprocessor.kernel_name=$IPYTHON_KERNEL 
      --ExecutePreprocessor.timeout=$NBCONVERT_TIMEOUT
```
From Richards PR: https://github.com/ramp-kits/meg/commit/2ad0122098e9c43c665214a6477edaf62cabc5f8

**Comment by maikia** [comment]
@lucyleeow I think Richard did himself: https://github.com/ramp-kits/meg/commit/3bbfc7f8c9533ce90738a884f56e8ef3391bc97e

feel free to add it back in

**Comment by lucyleeow** [comment]
Maybe @hoechenberger would know why travis is failing, he made the last changes.

It looks the same as other travis files (e.g. [el nino](https://github.com/ramp-kits/el_nino/blob/master/.travis.yml))

**Comment by lucyleeow** [comment]
It's weird. I have re-run it....

**Comment by lucyleeow** [comment]
The error:
```
$ jupyter nbconvert --execute meg_starting_kit.ipynb --ExecutePreprocessor.kernel_name=$IPYTHON_KERNEL
Traceback (most recent call last):

  File "/home/travis/miniconda/envs/testenv/bin/jupyter-nbconvert", line 8, in <module>

    sys.exit(main())

  File "/home/travis/miniconda/envs/testenv/lib/python3.8/site-packages/jupyter_core/application.py", line 270, in launch_instance

    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)

  File "/home/travis/miniconda/envs/testenv/lib/python3.8/site-packages/traitlets/config/application.py", line 837, in launch_instance

    app.start()

  File "/home/travis/miniconda/envs/testenv/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 345, in start

    self.convert_notebooks()

  File "/home/travis/miniconda/envs/testenv/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 507, in convert_notebooks

    raise ValueError(

ValueError: Please specify an output format with '--to <format>'.

The following formats are available: ['asciidoc', 'custom', 'html', 'latex', 'markdown', 'notebook', 'pdf', 'python', 'rst', 'script', 'slides', 'webpdf']
```
is odd because
> The default output format is HTML, for which the --to argument may be omitted:

from: https://nbconvert.readthedocs.io/en/latest/usage.html

I would say it's okay to ignore this and merge...

**Comment by hoechenberger** [comment]
I can have a look shortly

**Review by agramfort — APPROVED** [review]

**Comment by maikia** [comment]
@lucyleeow @agramfort 

I am ok to merge it if @hoechenberger has no additional comments.
However that means we will face the same problem with any new PR

**Comment by agramfort** [comment]
I would avoid merging a PR that breaks the CI

**Comment by lucyleeow** [comment]
I pulled this locally and nbconvert worked fine. I think it must be a travis issue. I made a small formatting change but I don't think this is causing the failure.

**Comment by lucyleeow** [comment]
@agramfort do you know why we install nbconvert via: `nbconvert[test]`

It's done in most kits.

**Comment by maikia** [comment]
Thanks @lucyleeow and @hichamjanati

**Comment by lucyleeow** [comment]
Argh not so fast.

**Comment by lucyleeow** [comment]
It shouldn't have been failing, not sure if it is a nbconvert version problem.

@agramfort do you know why we install `nbconvert[test]` ??

**Comment by agramfort** [comment]
no idea

**Comment by hoechenberger** [comment]
Sorry for being unresponsive. I will look into this later tonight.

**Comment by hoechenberger** [comment]
Oh. Wait. Is there anything left to do for me at all? 😁

**Pull request merged**
